plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id "com.netflix.dgs.codegen" version "6.0.3"
}

group = 'kz.anilenses'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Configuration settings for the Java code generation task based on GraphQL schema
generateJava {
    schemaPaths = ["${projectDir}/src/main/resources/schema"] // List of directories containing schema files
    packageName = 'team.alabs.nisp.appservice' // The package name to use to generate sources
    generateClient = false              // Enable generating the type safe query API
    typeMapping = [
            "BigDecimal" : "java.math.BigDecimal"
    ]
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

ext {
    set('netflixDgsVersion', "10.1.2")
}

dependencies {
    //dubbo
    implementation "org.apache.dubbo:dubbo-spring-boot-starter:${dubboVersion}"
    implementation "org.apache.dubbo:dubbo-dependencies-zookeeper-curator5:${dubboVersion}"

    //blaze persistence
    implementation "com.blazebit:blaze-persistence-core-api-jakarta:${blazePersistenceVersion}"
    runtimeOnly "com.blazebit:blaze-persistence-core-impl-jakarta:${blazePersistenceVersion}"
    runtimeOnly "com.blazebit:blaze-persistence-integration-hibernate-6.2:${blazePersistenceVersion}"
    implementation "com.blazebit:blaze-persistence-entity-view-api-jakarta:${blazePersistenceVersion}"
    runtimeOnly "com.blazebit:blaze-persistence-entity-view-impl-jakarta:${blazePersistenceVersion}"
    compileOnly "com.blazebit:blaze-persistence-entity-view-processor-jakarta:${blazePersistenceVersion}"
    implementation "com.blazebit:blaze-persistence-integration-entity-view-spring-6.0:${blazePersistenceVersion}"

    implementation('org.springframework.boot:spring-boot-starter-data-jpa') {
        exclude group: 'org.hibernate', module: 'hibernate-core'
    }

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    //netflix dgs (graphql-engine)
    implementation 'com.netflix.graphql.dgs:graphql-dgs-spring-graphql-starter'
    implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:7.5.3"))
    implementation "com.netflix.graphql.dgs:graphql-dgs-extended-scalars"

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'

    //inter-project
    implementation 'kz.anilenses:exception-handler-kit:1.0.0-SNAPSHOT'
    implementation 'kz.anilenses:web-commons:1.0.0-SNAPSHOT'

    compileOnly 'org.projectlombok:lombok'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'

    // mapper
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    //jpamodelgen - generates metamodel objects to provide type safety in building criteria queries
    annotationProcessor 'org.hibernate:hibernate-jpamodelgen:6.3.1.Final'

    //tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.netflix.graphql.dgs:graphql-dgs-spring-graphql-starter-test'
    testImplementation 'org.springframework.graphql:spring-graphql-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

task prefixNewMigrations(group: 'flyway') {

    fileTree(dir: getProjectDir().toString() + '/src/main/resources/db/migration').exclude({ isFilePrefixed(it.file)}).exclude('callbacks').each {
        file -> doLast {
            def timestamp = new Date().format('yyyyMMddHHmmssSSS', TimeZone.getTimeZone('GMT'))
            println "Renaming $file.name to V${timestamp}__$file.name"
            def migrationPrefix = "V"
            file.renameTo("$file.parentFile.absolutePath$file.separator$migrationPrefix${timestamp}__$file.name")
            // Sleep for a moment to avoid prefix conflicts when renaming multiple files
            sleep(1*1000)
        }
    }
}

static def isFilePrefixed(file) {
    return (file.name ==~ '^V.*__.*\\.sql\$') || (file.name ==~ '^R__.*\\.sql\$') || (file.name ==~ '^\\d+__.*\\.sql\$')
}

dependencyManagement {
    imports {
        mavenBom "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:${netflixDgsVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
