# ====================================================
# =                 QUERY                            =
# ====================================================
extend type Query {
    products(category: ProductCategoryEnum!, pageable: PageableInput!): ProductPage!
    product(id: Long!, category: ProductCategoryEnum!): ProductInterface!
}

# ====================================================
# =                 TYPES                            =
# ====================================================
type ProductPage {
    "Информация о товарах"
    content: [ProductInterface]!

    "Общее количество"
    totalElements: Long!
}

# ====================================================
# =                 ENUMS                            =
# ====================================================
enum ProductCategoryEnum {
    LENSES
}